### ISSUE TITLE
Backfill error: `invalid byte sequence for encoding "UTF8": 0x00`

### ISSUE THREAD

**Issue by gskril** [gskril/farcaster-indexer#33]
Error thrown when backfilling FIDs 308901 - 309000. The job stopped at 71%, so the issue is likely happening somewhere between FID 308970 - 308975.

**Comment by jiayuxiaochaoren** [comment]
Same problem.
It seems to be encoding content has '$'?
``` err: {
      "type": "DatabaseError",
      "message": "invalid byte sequence for encoding \"UTF8\": 0x00",
      "stack":
          error: invalid byte sequence for encoding "UTF8": 0x00
              at /app/node_modules/pg/lib/client.js:526:17
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:69:28)
              at async file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
              at async DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
              at async DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
              at async InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:686:24)
              at async insertCasts (file:///app/dist/api/cast.js:15:13)
              at async Worker.handleJob [as processFn] (file:///app/dist/lib/backfill.js:83:9)
              at async Worker.processJob (/app/node_modules/bullmq/dist/cjs/classes/worker.js:430:28)
              at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:88:41)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
              at async DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
              at async DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
              at async InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:686:24)
              at async insertCasts (file:///app/dist/api/cast.js:15:13)
              at async Worker.handleJob [as processFn] (file:///app/dist/lib/backfill.js:83:9)
              at async Worker.processJob (/app/node_modules/bullmq/dist/cjs/classes/worker.js:430:28)
              at async Worker.retryIfFailed (/app/node_modules/bullmq/dist/cjs/classes/worker.js:619:24)
      "length": 148,
      "name": "error",
      "severity": "ERROR",
      "code": "22021",
      "where": "unnamed portal parameter $157",
      "file": "mbutils.c",
      "line": "1723",
      "routine": "report_invalid_encoding"
    }
```
